id: P005443
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC57
  title: བཤེས་པའི་སྤྲིངས་ཡིག་དང་སྤྱོད་འཇུག་སོགས།
  author: ''
  volumes:
    8e1b41dd85dd4db0b85ce3f011b528d4:
      image_group_id: I2PD18751
      title: ''
      volume_number: 1
      total_pages: 150
