id: IB48EF478
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:32:56+00:00'
last_modified: '2022-06-08T03:07:31.114957+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC57
  title: བཤེས་པའི་སྤྲིངས་ཡིག་དང་སྤྱོད་འཇུག་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A7D8:
      image_group_id: I2PD18751
      title: ''
      total_pages: 150
      order: 1
      base_file: A7D8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
